# Fonts
font_family JetBrains Mono
font_size 11
disable_ligatures never
modify_font cell_height 2px

# URL
url_color #4287F5
url_style curly
url_prefixes http https file ftp git

# Mouse and cursor
mouse_hide_wait 1.0
cursor #19F0FF
cursor_text_color #000000
cursor_trail 200
cursor_trail_decay 0.1 0.4

# Aesthetics
background_opacity 0.8
scrollbar never
window_margin_width 5

#========== ANSI Foregrounds ==========

# Color0 - White (supposed to be black in standard ANSI)
color0 #FFFFFF
# Color1 - Red
color1 #CC0404
# Color2 - Green
color2 #0CC71C
# Color3 - Orange (Supposed to be yellow in standard ANSI)
color3 #FFA305
# Color4 - Blue
color4 #3377FF
# Color5 - Purple (Supposed to be magenta in standard ANSI)
color5 #BB0FFF
# Color6 - Cyan
color6 #19F0FF
# Color7 - White
color7 #FFFFFF


#========== ANSI Backgrounds ==========

# Color8 - White (Supposed to be a brighter black in standard ASNI)
color8 #FFFFFF
# Color9 - Bright Red
color9 #FFFFFF
# Color10 - Bright Green
color10 #00FF00
# Color11 - Bright Orange (Supposed to be bright yellow in standard ANSI)
color11 #FFC400
# Color12 - Bright Blue
color12 #0000FF
# Color13 - Bright Purple (Supposed to be bright magenta in standard ANSI)
color13 #D70FFF
# Color14 - Bright Cyan
color14 #00FFFF
# Color15 - White
color15 #FFFFFF
